services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "echo \"Starting MCC!\" && npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - claws-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://localhost:27017/
    networks:
      - claws-network

networks:
  claws-network:
    driver: bridge